Dev
LagrangeLabs/ii-admin-ui pull request #13
Opened 2021-04-25 02:39 UTC by xueyang996

IAert 组件CR

2021-04-25 02:56 UTC, Bian2017 reviewed
要不继续修改下

2021-04-25 02:56 UTC, Bian2017 commented on src/components/i-alert/index.less
> +  background-color: rgba(47, 195, 124, 0.1);
公共颜色要抽取出来，包括background-color，color

2021-04-25 02:56 UTC, Bian2017 commented on src/components/i-alert/index.less
> +    font-size: 13px;
通用font-size也抽出来，可以分几个等级？基本、中等、大，也可以直接引用ant design的变量

2021-04-25 02:56 UTC, Bian2017 commented on src/components/i-alert/index.tsx
> +  return jsxEle;
为什么不直接return，而通过变量来走？

2021-04-25 02:56 UTC, Bian2017 commented on src/components/i-alert/index.tsx
> +    }
为什么有的地方有换行符，有的地方没有？如果unstable_action为false，下面的warnTxt 是不是会有个换行显示？

2021-04-25 02:56 UTC, Bian2017 commented on src/components/i-alert/index.tsx
> +  );
jsxEle这个定义里面没有用到warnTxt，不太清楚定义这个warnTxt这个变量作用

2021-04-25 03:06 UTC, IVLIU commented on src/components/i-alert/index.tsx
> +    }
第一行无换行符

2021-04-25 03:07 UTC, IVLIU commented on src/components/i-alert/index.tsx
> +  );
warnTxt 是一个局部变量，定义在useEffect中的，只是做警告提示用的

2021-04-25 03:07 UTC, IVLIU commented on src/components/i-alert/index.less
> +  background-color: rgba(47, 195, 124, 0.1);
带有透明度的颜色是否需要提取

2021-04-25 03:10 UTC, IVLIU commented on src/components/i-alert/index.tsx
> +  return jsxEle;
单纯编程习惯，改下就好了

2021-04-25 03:11 UTC, IVLIU commented on src/components/i-alert/index.tsx
> +    }
unstable变量都有相应的类型定义，所定义的几个unstable是没有boolean的

2021-04-25 05:31 UTC, IVLIU commented on src/components/i-alert/index.tsx
> +  return jsxEle;
已修改

2021-04-25 05:32 UTC, IVLIU commented on src/components/i-alert/index.tsx
> +    }
已修改

2021-04-26 01:38 UTC, Bian2017 commented on src/components/i-alert/index.less
> +  background-color: rgba(47, 195, 124, 0.1);
看下ant design这块是怎么做的？我记得是有个基础色系，然后会定义透明等级函数

2021-05-11 06:13 UTC, Bian2017 requested changes

2021-05-11 06:13 UTC, Bian2017 commented on src/components/i-smallcard/index.tsx
> +  // iconClass?: string;
如果不需要iconClass就删了吧

2021-05-11 06:13 UTC, Bian2017 commented on src/components/i-smallcard/index.tsx
> +        {!tips ? null : (
这个地方应该不需要三元运算符，应该直接 tips && (....)

2021-05-11 06:13 UTC, Bian2017 commented on src/components/i-smallcard/index.tsx
> +            key="tips"
应该不需要加key，不清楚此处加key="tips"作用

2021-05-11 06:13 UTC, Bian2017 commented on config/menus.js
> +        'components/ISmallCard',
就叫统计卡片吧，专门用于统计时用的。看UI稿，分主要的和次要的，主要的卡片要不叫IStatisticsCard，次要的要不叫IStatisticsSubCard，

2021-05-11 06:13 UTC, Bian2017 commented on docs/components/ISmallCard.css
> +  color: rgb(70, 52, 231);
颜色值抽出来，放到theme中，此处引用变量。其他地方一样

2021-05-11 06:13 UTC, Bian2017 commented on docs/components/ISmallCard.css
> +  background: rgba(147, 229, 147, 0.3);
此处将颜色变量抽取出来，可以通过fade来修改透明度。其他地方同理

2021-05-11 06:13 UTC, Bian2017 commented on docs/components/ISmallCard.md
> +# ISmallCard 组件
修改名称

2021-05-11 06:13 UTC, Bian2017 commented on src/components/i-smallcard/index.tsx
> +    unitClass,
建议采用 unitClass = '' ,即默认值方式，className、titleClass、valueClass、unitClass同理

2021-05-11 06:13 UTC, Bian2017 commented on src/components/i-smallcard/index.tsx
> +export type SmallCardProps = {
此处props不应该采用type，应该是export interface ISmallCardProps，其中I表示interface的意思

2021-05-11 06:13 UTC, Bian2017 commented on src/components/i-smallcard/index.tsx
> +  value?: string | number;
value直接定义成ReactNode，其他节点是不是也可以这样，unit等等

2021-05-11 06:13 UTC, Bian2017 commented on src/components/i-smallcard/index.tsx
> +        </span>
建议写成value && \<span>{value}\</span>， unit同理

2021-05-11 06:13 UTC, Bian2017 commented on src/components/i-alert/index.less
> +
可以参照ant design的样式，在components目录下有个style目录，style目录有份themes目录，在这里面会有一些基色值

2021-05-11 06:31 UTC, Bian2017 requested changes
建议更改下

2021-05-11 06:31 UTC, Bian2017 commented on src/components/i-smallcard/index.less
> +    }
参照ant design的基准色值，https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less ，样式都可以已变量形成提取出来。为了避免和ant design的样式有冲突，自定义的变量可以已`ii-` 开头

2021-05-12 02:13 UTC, xueyang996 commented on src/index.tsx
> +export { default as ISmallCard } from './components/i-smallcard';
文件夹 命名要改为 './components/i-small-card'

2021-05-12 02:25 UTC, merged

2021-05-21 07:05 UTC, heyang-xing commented on config/menus.js
> +        'components/ISmallCard',
优先改了IStatisticsSubCard。

2021-05-21 07:06 UTC, heyang-xing commented on docs/components/ISmallCard.css
> +  color: rgb(70, 52, 231);
已修改。

2021-05-21 07:06 UTC, heyang-xing commented on docs/components/ISmallCard.css
> +  background: rgba(147, 229, 147, 0.3);
目前这里是css文件，不需要，是示例的代码。

2021-05-21 07:07 UTC, heyang-xing commented on docs/components/ISmallCard.md
> +# ISmallCard 组件
已修改。

2021-05-21 07:08 UTC, heyang-xing commented on src/components/i-smallcard/index.less
> +    }
已处理color。

2021-05-21 07:09 UTC, heyang-xing commented on src/components/i-smallcard/index.tsx
> +export type SmallCardProps = {
已修改。

2021-05-21 07:10 UTC, heyang-xing commented on src/components/i-smallcard/index.tsx
> +    unitClass,
暂时不需要，本身就主要支持number或者string，不支持较多数据。

2021-05-21 07:10 UTC, heyang-xing commented on src/components/i-smallcard/index.tsx
> +        {!tips ? null : (
已修改。

2021-05-21 07:10 UTC, heyang-xing commented on src/components/i-smallcard/index.tsx
> +            key="tips"
已删除。

2021-05-21 07:12 UTC, heyang-xing commented on src/components/i-smallcard/index.tsx
> +        </span>
已经修改。

2021-05-21 07:16 UTC, heyang-xing commented on src/index.tsx
> +export { default as ISmallCard } from './components/i-smallcard';
已经改成i-statistics-sub-card。